[package]
name = "warp_ws_example"
version = "0.1.0"
edition = "2018"

# Add necessary dependencies
[dependencies]
warp = "0.3"
tungstenite = "0.15"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
serde = "1.0"
serde_json = "1.0"
