import { html, T } from "helpers";
const iconNames = [
  "chevron-up",
  "chevron-down",
  "chevrons-down",
  "chevrons-right",
  "navigation",
  "monitor",
  "star",
  "calendar",
  "app-window",
  "clapperboard",
  "users",
  "table",
  "user",
  "tag",
  "tags",
  "home",
  "heart",
  "heart-pulse",
  "spinner",
  "smartphone",
  "layout",
  "layout-template",
  "git-branch",
  "type",
  "clock",
  "git-commit",
  "git-merge",
  "alert-triangle",
  "loader",
  "bell",
  "message-circle",
  "message-square",
  "bar-chart",
  "mouse-pointer",
  "edit",
  "credit-card",
  "sidebar",
  "box",
  "minus",
  "list",
  "layers",
  "link",
  "more-vertical",
  "droplet",
  "upload-cloud",
  "radio",
  "sliders",
  "toggle-right",
  "wand",
  "package",
  "database",
  "smile",
];

export default {
  tag: "uix-icon",
  props: {
    iconSet: T.string({ defaultValue: "lucide" }),
    name: T.string(),
    size: T.string({ defaultValue: "" }),
  },
  theme: {
    "uix-icon": {
      _base: ({ name, iconSet }) => `i-${iconSet}-${name} block`,
    },
    "uix-icon__icons": iconNames.map((name) => "i-lucide-" + name).join(" "),
  },
  render() {
    return html``;
  },
};
