export const defaultTheme = {
    colors: {
      default: "gray",
      button: "white",
      primary: "blue",
      secondary: "pink",
      accent: "yellow",
      base: "gray",
      info: "teal",
      success: "green",
      warning: "orange",
      error: "red",
    },
    iconFontFamily: "lucide",
    backgroundColor: "bg-gray-100",
    backgroundSecondaryColor: "bg-gray-600",
    cardBackgroundColor: "bg-white",
    borderRadius: "rounded-md",
    fontStyles: "font-bold leading-5 hover:leading-5",
    textVariant: "700",
    defaultTextColor: "text-gray-700",
    secondaryTextColor: "text-gray-100",
    activeTextColor: "text-blue-600",
    hoverTextColor: "hover:text-blue-400",
    borderStyles: "border border-gray-300",
    hoverBorder: "hover:border-blue-400",
    borderWidth: "border-b-2",
    flexCenter: "flex flex-row items-center gap-2 text-center justify-center",
    baseVariants: {
      bgVariation: "200",
      textVariation: "700",
      hoverBgVariation: "100",
      hoverTextVariation: "800",
      accentVariation: "400",
    },
    reverseVariants: {
      bgVariation: "700",
      textVariation: "white",
      hoverBgVariation: "600",
      hoverTextVariation: "100",
      accentVariation: "200",
    },
  };
  