const T = self.T;

export default {
  communities: {
    name: T.string({ primary: true }),
    description: T.string(),
    headline: T.string(),
    image: T.string(),
    announcementGroup: T.string(),
    groups: T.many("groups"),
    tags: T.many("tags"),
    owner: T.string(),
    admins: T.many("users"),
    createdAt: T.date(),
    updatedAt: T.date(),
  },
  groups: {
    name: T.string({ primary: true }),
    url: T.string(),
    image: T.string(),
    users: T.number(),
    admins: T.many("users"),
    frequency: T.string(),
    size: T.number(),
    description: T.string(),
    headline: T.string(),
    status: T.string(),
    featured: T.boolean(),
    tags: T.many("tags"),
    communityId: T.string(),
    createdAt: T.date(),
    updatedAt: T.date(),
  },
  tags: {
    name: T.string({ primary: true }),
    groups: T.many("groups"),
    communities: T.many("communities"),
    city: T.boolean(),
    country: T.boolean(),
  },
  users: {
    name: T.string({ primary: true }),
    avatar: T.string(),
    groups: T.many("groups"),
    communities: T.many("groups"),
    groupsAdminOf: T.many("groups"),
    communitiesAdminOf: T.many("communities"),
  },
};
